const rawData = [
    // DAY 01
    { day: 1, word: "tall", meaning: "키가 큰, 높은" },
    { day: 1, word: "cut", meaning: "베다; 자르다" },
    { day: 1, word: "nice", meaning: "멋진, 좋은, 괜찮은" },
    { day: 1, word: "have", meaning: "가지다; 먹다, 마시다" },
    { day: 1, word: "actor", meaning: "배우" },
    { day: 1, word: "many", meaning: "많은" },
    { day: 1, word: "see", meaning: "보다; 알다, 이해하다" },
    { day: 1, word: "from", meaning: "~에서(부터); ~부터" },
    { day: 1, word: "what", meaning: "무엇, 어떤 것; 무슨, 어떤" },
    { day: 1, word: "old", meaning: "오래된; 나이 든, 늙은" },
    { day: 1, word: "meet", meaning: "만나다" },
    { day: 1, word: "make", meaning: "만들다" },
    { day: 1, word: "friend", meaning: "친구, 벗" },
    { day: 1, word: "cap", meaning: "(앞에 챙이 달린) 모자" },
    { day: 1, word: "large", meaning: "큰, 넓은; 많은" },
    { day: 1, word: "heavy", meaning: "무거운; (양, 정도가) 많은, 심한" },
    { day: 1, word: "long", meaning: "(길이, 거리가) 긴; (시간이) 오랜" },
    { day: 1, word: "school", meaning: "학교" },
    { day: 1, word: "come from", meaning: "~ 출신이다, ~에서 오다" },
    { day: 1, word: "be going to", meaning: "~할 것이다, ~할 예정이다" },

    // DAY 02
    { day: 2, word: "happy", meaning: "행복한" },
    { day: 2, word: "room", meaning: "방" },
    { day: 2, word: "dance", meaning: "춤추다; 춤, 댄스" },
    { day: 2, word: "fun", meaning: "재미, 즐거움; 재미있는" },
    { day: 2, word: "clean", meaning: "깨끗한; 청소하다" },
    { day: 2, word: "bean", meaning: "콩" },
    { day: 2, word: "light", meaning: "빛; (전깃)불, 전등; 가벼운" },
    { day: 2, word: "for", meaning: "~을 위해; ~ 동안" },
    { day: 2, word: "good", meaning: "좋은, 훌륭한; 즐거운, 기쁜" },
    { day: 2, word: "short", meaning: "(길이, 거리가) 짧은; 키가 작은" },
    { day: 2, word: "eat", meaning: "먹다" },
    { day: 2, word: "too", meaning: "너무; 또한, 게다가" },
    { day: 2, word: "lunch", meaning: "점심 (식사)" },
    { day: 2, word: "wait", meaning: "기다리다" },
    { day: 2, word: "student", meaning: "학생" },
    { day: 2, word: "model", meaning: "모형, 모델" },
    { day: 2, word: "out", meaning: "밖에, 밖으로" },
    { day: 2, word: "young", meaning: "어린, 젊은" },
    { day: 2, word: "go to school", meaning: "학교에 다니다" },
    { day: 2, word: "make friends", meaning: "친구가 되다, 친해지다" },

    // DAY 03
    { day: 3, word: "all", meaning: "모든; 모두" },
    { day: 3, word: "city", meaning: "도시" },
    { day: 3, word: "day", meaning: "하루, 날; 낮" },
    { day: 3, word: "smart", meaning: "영리한, 똑똑한" },
    { day: 3, word: "look", meaning: "보다; (~하게) 보이다" },
    { day: 3, word: "teacher", meaning: "교사, 선생" },
    { day: 3, word: "watch", meaning: "보다; 손목시계" },
    { day: 3, word: "to", meaning: "~으로, ~에; ~까지" },
    { day: 3, word: "house", meaning: "집, 주택" },
    { day: 3, word: "hobby", meaning: "취미" },
    { day: 3, word: "like", meaning: "좋아하다; ~처럼, ~와 같이" },
    { day: 3, word: "new", meaning: "새, 새로운" },
    { day: 3, word: "ago", meaning: "~ 전에, 이전에" },
    { day: 3, word: "classmate", meaning: "급우, 반 친구" },
    { day: 3, word: "dancer", meaning: "춤추는 사람, 무용수" },
    { day: 3, word: "dinner", meaning: "저녁 (식사)" },
    { day: 3, word: "dirty", meaning: "더러운" },
    { day: 3, word: "study", meaning: "공부(하다); 연구(하다)" },
    { day: 3, word: "have fun", meaning: "즐기다, 재미있게 놀다" },
    { day: 3, word: "eat out", meaning: "외식하다" },

    // DAY 04
    { day: 4, word: "enter", meaning: "들어가다; 입학하다" },
    { day: 4, word: "body", meaning: "몸, 신체" },
    { day: 4, word: "act", meaning: "행동하다; 행동, 행위" },
    { day: 4, word: "bad", meaning: "나쁜, 불쾌한; 해로운" },
    { day: 4, word: "classroom", meaning: "교실, 강의실" },
    { day: 4, word: "flower", meaning: "꽃" },
    { day: 4, word: "color", meaning: "색, 색깔" },
    { day: 4, word: "in", meaning: "~(안)에서; ~(동안)에" },
    { day: 4, word: "minute", meaning: "(시간의 단위) 분; 잠깐" },
    { day: 4, word: "sand", meaning: "모래" },
    { day: 4, word: "star", meaning: "별; 스타" },
    { day: 4, word: "wet", meaning: "젖은, 축축한" },
    { day: 4, word: "yesterday", meaning: "어제" },
    { day: 4, word: "hot", meaning: "뜨거운, 더운; 매운" },
    { day: 4, word: "late", meaning: "늦은, 지각한; 늦게" },
    { day: 4, word: "well", meaning: "잘, 훌륭하게; 건강한" },
    { day: 4, word: "beach", meaning: "해변, 바닷가" },
    { day: 4, word: "who", meaning: "누구" },
    { day: 4, word: "look like", meaning: "~처럼 보이다" },
    { day: 4, word: "all day", meaning: "하루 종일" },

    // DAY 05
    { day: 5, word: "feel", meaning: "느끼다; (기분이) 들다" },
    { day: 5, word: "cold", meaning: "추운, 차가운; 감기" },
    { day: 5, word: "class", meaning: "학급, 반; 수업" },
    { day: 5, word: "sad", meaning: "슬픈" },
    { day: 5, word: "family", meaning: "가족, 가정" },
    { day: 5, word: "really", meaning: "정말로, 아주; 실제로" },
    { day: 5, word: "hour", meaning: "한 시간" },
    { day: 5, word: "at", meaning: "~에(서)" },
    { day: 5, word: "rain", meaning: "비; 비가 오다" },
    { day: 5, word: "dry", meaning: "마른; 마르다" },
    { day: 5, word: "time", meaning: "시각; 시간; 때" },
    { day: 5, word: "last", meaning: "마지막의; 지난" },
    { day: 5, word: "morning", meaning: "아침, 오전" },
    { day: 5, word: "live", meaning: "살다; 살아있는" },
    { day: 5, word: "movie", meaning: "영화" },
    { day: 5, word: "sour", meaning: "신; 상한" },
    { day: 5, word: "meat", meaning: "고기" },
    { day: 5, word: "lake", meaning: "호수" },
    { day: 5, word: "look for", meaning: "~을 찾다" },
    { day: 5, word: "feel like", meaning: "~하고 싶다; ~처럼 느끼다" },

    // DAY 06
    { day: 6, word: "again", meaning: "다시, 또" },
    { day: 6, word: "home", meaning: "집; 집에" },
    { day: 6, word: "kid", meaning: "아이, 어린이" },
    { day: 6, word: "baker", meaning: "제빵사" },
    { day: 6, word: "cool", meaning: "시원한; 멋진" },
    { day: 6, word: "ready", meaning: "준비가 된" },
    { day: 6, word: "test", meaning: "시험; 검사" },
    { day: 6, word: "with", meaning: "~와 함께; ~로" },
    { day: 6, word: "week", meaning: "주, 일주일" },
    { day: 6, word: "far", meaning: "멀리; 먼" },
    { day: 6, word: "son", meaning: "아들" },
    { day: 6, word: "town", meaning: "(소)도시, 마을" },
    { day: 6, word: "rainy", meaning: "비가 오는" },
    { day: 6, word: "hair", meaning: "머리(카락)" },
    { day: 6, word: "funny", meaning: "우스운, 재미있는" },
    { day: 6, word: "sea", meaning: "바다" },
    { day: 6, word: "night", meaning: "밤, 야간" },
    { day: 6, word: "people", meaning: "사람들; 국민" },
    { day: 6, word: "be good at", meaning: "~을 잘하다" },
    { day: 6, word: "watch out", meaning: "조심하다, 주의하다" },

    // DAY 07
    { day: 7, word: "say", meaning: "말하다" },
    { day: 7, word: "where", meaning: "어디에, 어디로" },
    { day: 7, word: "bakery", meaning: "제과점" },
    { day: 7, word: "word", meaning: "단어, 말" },
    { day: 7, word: "thin", meaning: "얇은; 마른" },
    { day: 7, word: "play", meaning: "놀다; 경기하다; 연주하다" },
    { day: 7, word: "child", meaning: "아이; 자식" },
    { day: 7, word: "after", meaning: "~후에; 뒤에" },
    { day: 7, word: "start", meaning: "시작하다; 출발하다" },
    { day: 7, word: "dark", meaning: "어두운" },
    { day: 7, word: "read", meaning: "읽다" },
    { day: 7, word: "evening", meaning: "저녁" },
    { day: 7, word: "open", meaning: "열린; 열다" },
    { day: 7, word: "every", meaning: "모든; 매~" },
    { day: 7, word: "fill", meaning: "채우다" },
    { day: 7, word: "name", meaning: "이름" },
    { day: 7, word: "floor", meaning: "바닥; 층" },
    { day: 7, word: "knife", meaning: "칼" },
    { day: 7, word: "again and again", meaning: "몇 번이고, 되풀이해서" },
    { day: 7, word: "be happy with", meaning: "~에 만족하다" },

    // DAY 08
    { day: 8, word: "easy", meaning: "쉬운" },
    { day: 8, word: "cute", meaning: "귀여운" },
    { day: 8, word: "know", meaning: "알다" },
    { day: 8, word: "daughter", meaning: "딸" },
    { day: 8, word: "player", meaning: "선수; 연주자" },
    { day: 8, word: "window", meaning: "창문" },
    { day: 8, word: "close", meaning: "닫다; 가까운" },
    { day: 8, word: "of", meaning: "~의; ~중의" },
    { day: 8, word: "cook", meaning: "요리하다; 요리사" },
    { day: 8, word: "then", meaning: "그때; 그 다음에" },
    { day: 8, word: "fat", meaning: "뚱뚱한; 지방" },
    { day: 8, word: "snow", meaning: "눈; 눈이 오다" },
    { day: 8, word: "handsome", meaning: "잘생긴" },
    { day: 8, word: "sick", meaning: "아픈" },
    { day: 8, word: "month", meaning: "달, 월" },
    { day: 8, word: "walk", meaning: "걷다; 산책" },
    { day: 8, word: "rock", meaning: "바위, 돌" },
    { day: 8, word: "next", meaning: "다음의; 다음에" },
    { day: 8, word: "after school", meaning: "방과 후에" },
    { day: 8, word: "say hello to", meaning: "~에게 인사하다" },

    // DAY 09
    { day: 9, word: "end", meaning: "끝나다; 끝" },
    { day: 9, word: "year", meaning: "해, 연; 나이" },
    { day: 9, word: "group", meaning: "무리, 집단" },
    { day: 9, word: "there", meaning: "거기에, 그곳에" },
    { day: 9, word: "afternoon", meaning: "오후" },
    { day: 9, word: "wear", meaning: "입다(신다/쓰다)" },
    { day: 9, word: "theater", meaning: "극장" },
    { day: 9, word: "on", meaning: "~위에; ~에" },
    { day: 9, word: "hear", meaning: "듣다, 들리다" },
    { day: 9, word: "story", meaning: "이야기" },
    { day: 9, word: "sound", meaning: "소리; ~하게 들리다" },
    { day: 9, word: "hungry", meaning: "배고픈" },
    { day: 9, word: "run", meaning: "달리다; 경영하다" },
    { day: 9, word: "kind", meaning: "친절한; 종류" },
    { day: 9, word: "round", meaning: "둥근" },
    { day: 9, word: "loud", meaning: "시끄러운, 큰 소리의" },
    { day: 9, word: "push", meaning: "밀다" },
    { day: 9, word: "bright", meaning: "밝은; 영리한" },
    { day: 9, word: "next to", meaning: "~ 옆에" },
    { day: 9, word: "fill in", meaning: "~을 채우다, 작성하다" },

    // DAY 10
    { day: 10, word: "air", meaning: "공기; 공중" },
    { day: 10, word: "hard", meaning: "어려운; 단단한; 열심히" },
    { day: 10, word: "listen", meaning: "듣다" },
    { day: 10, word: "full", meaning: "가득 찬; 배부른" },
    { day: 10, word: "music", meaning: "음악" },
    { day: 10, word: "animal", meaning: "동물" },
    { day: 10, word: "beautiful", meaning: "아름다운" },
    { day: 10, word: "up", meaning: "위로; ~위에" },
    { day: 10, word: "weekend", meaning: "주말" },
    { day: 10, word: "sit", meaning: "앉다" },
    { day: 10, word: "put", meaning: "놓다, 두다" },
    { day: 10, word: "warm", meaning: "따뜻한" },
    { day: 10, word: "pull", meaning: "당기다" },
    { day: 10, word: "north", meaning: "북쪽; 북쪽의" },
    { day: 10, word: "noise", meaning: "소음, 소리" },
    { day: 10, word: "door", meaning: "문" },
    { day: 10, word: "size", meaning: "크기, 치수" },
    { day: 10, word: "how", meaning: "어떻게; 얼마나" },
    { day: 10, word: "go on", meaning: "계속되다" },
    { day: 10, word: "in the end", meaning: "마침내" },

    // DAY 11
    { day: 11, word: "fly", meaning: "날다; 파리" },
    { day: 11, word: "way", meaning: "길; 방법" },
    { day: 11, word: "earth", meaning: "지구; 땅" },
    { day: 11, word: "voice", meaning: "목소리" },
    { day: 11, word: "get", meaning: "얻다; 도착하다; 되다" },
    { day: 11, word: "thick", meaning: "두꺼운" },
    { day: 11, word: "knock", meaning: "두드리다, 노크하다" },
    { day: 11, word: "down", meaning: "아래로" },
    { day: 11, word: "fight", meaning: "싸우다; 싸움" },
    { day: 11, word: "fast", meaning: "빠른; 빨리" },
    { day: 11, word: "ride", meaning: "타다" },
    { day: 11, word: "grow", meaning: "자라다; 기르다" },
    { day: 11, word: "pocket", meaning: "주머니" },
    { day: 11, word: "sweet", meaning: "달콤한" },
    { day: 11, word: "hit", meaning: "치다, 때리다" },
    { day: 11, word: "mountain", meaning: "산" },
    { day: 11, word: "loudly", meaning: "큰 소리로" },
    { day: 11, word: "easily", meaning: "쉽게" },
    { day: 11, word: "make fun of", meaning: "~을 놀리다" },
    { day: 11, word: "put on", meaning: "입다, 쓰다" },

    // DAY 12
    { day: 12, word: "sky", meaning: "하늘" },
    { day: 12, word: "bicycle", meaning: "자전거" },
    { day: 12, word: "today", meaning: "오늘" },
    { day: 12, word: "angry", meaning: "화난" },
    { day: 12, word: "slow", meaning: "느린" },
    { day: 12, word: "back", meaning: "뒤로; 등; 뒤쪽" },
    { day: 12, word: "rice", meaning: "쌀, 밥" },
    { day: 12, word: "about", meaning: "~에 대해; 대략" },
    { day: 12, word: "person", meaning: "사람" },
    { day: 12, word: "cry", meaning: "울다; 외치다" },
    { day: 12, word: "hat", meaning: "모자" },
    { day: 12, word: "deep", meaning: "깊은" },
    { day: 12, word: "parent", meaning: "부모" },
    { day: 12, word: "drive", meaning: "운전하다" },
    { day: 12, word: "often", meaning: "종종, 자주" },
    { day: 12, word: "find", meaning: "찾다, 발견하다" },
    { day: 12, word: "low", meaning: "낮은" },
    { day: 12, word: "fruit", meaning: "과일" },
    { day: 12, word: "at last", meaning: "마침내" },
    { day: 12, word: "on one's way", meaning: "도중에" },

    // DAY 13
    { day: 13, word: "date", meaning: "날짜; 데이트" },
    { day: 13, word: "talk", meaning: "말하다, 이야기하다" },
    { day: 13, word: "birthday", meaning: "생일" },
    { day: 13, word: "work", meaning: "일하다; 일" },
    { day: 13, word: "here", meaning: "여기에" },
    { day: 13, word: "country", meaning: "나라; 시골" },
    { day: 13, word: "price", meaning: "가격, 값" },
    { day: 13, word: "by", meaning: "~옆에; ~에 의해" },
    { day: 13, word: "alone", meaning: "혼자의; 혼자서" },
    { day: 13, word: "high", meaning: "높은; 높게" },
    { day: 13, word: "set", meaning: "놓다; (해)지다; 세트" },
    { day: 13, word: "wall", meaning: "벽" },
    { day: 13, word: "driver", meaning: "운전자" },
    { day: 13, word: "each", meaning: "각각의" },
    { day: 13, word: "slowly", meaning: "느리게, 천천히" },
    { day: 13, word: "table", meaning: "탁자" },
    { day: 13, word: "pick", meaning: "고르다; 줍다" },
    { day: 13, word: "cloud", meaning: "구름" },
    { day: 13, word: "find out", meaning: "알아내다" },
    { day: 13, word: "grow up", meaning: "자라다, 성장하다" },

    // DAY 14
    { day: 14, word: "alarm", meaning: "알람, 경보" },
    { day: 14, word: "weather", meaning: "날씨" },
    { day: 14, word: "some", meaning: "약간의, 몇몇의" },
    { day: 14, word: "think", meaning: "생각하다" },
    { day: 14, word: "buy", meaning: "사다" },
    { day: 14, word: "speak", meaning: "말하다, 연설하다" },
    { day: 14, word: "cloudy", meaning: "흐린" },
    { day: 14, word: "before", meaning: "~전에" },
    { day: 14, word: "ship", meaning: "배, 선박" },
    { day: 14, word: "east", meaning: "동쪽" },
    { day: 14, word: "everyone", meaning: "모든 사람" },
    { day: 14, word: "paint", meaning: "그리다; 페인트" },
    { day: 14, word: "tomorrow", meaning: "내일" },
    { day: 14, word: "map", meaning: "지도" },
    { day: 14, word: "half", meaning: "반, 절반" },
    { day: 14, word: "idea", meaning: "생각, 아이디어" },
    { day: 14, word: "holiday", meaning: "휴일" },
    { day: 14, word: "kick", meaning: "차다" },
    { day: 14, word: "by the way", meaning: "그나저나" },
    { day: 14, word: "up and down", meaning: "위아래로" },

    // DAY 15
    { day: 15, word: "life", meaning: "인생; 생명" },
    { day: 15, word: "board", meaning: "탑승하다; 판" },
    { day: 15, word: "brush", meaning: "솔; 닦다" },
    { day: 15, word: "tooth", meaning: "이(치아)" },
    { day: 15, word: "little", meaning: "작은; 어린" },
    { day: 15, word: "call", meaning: "전화하다; 부르다" },
    { day: 15, word: "market", meaning: "시장" },
    { day: 15, word: "around", meaning: "~주위에" },
    { day: 15, word: "speaker", meaning: "연설자; 스피커" },
    { day: 15, word: "fine", meaning: "좋은; 건강한" },
    { day: 15, word: "someday", meaning: "언젠가" },
    { day: 15, word: "much", meaning: "많은; 매우" },
    { day: 15, word: "sleep", meaning: "자다; 잠" },
    { day: 15, word: "use", meaning: "사용하다" },
    { day: 15, word: "why", meaning: "왜" },
    { day: 15, word: "present", meaning: "선물; 현재의" },
    { day: 15, word: "pet", meaning: "애완동물" },
    { day: 15, word: "key", meaning: "열쇠" },
    { day: 15, word: "get up", meaning: "일어나다" },
    { day: 15, word: "be made of", meaning: "~로 만들어지다" },

    // DAY 16
    { day: 16, word: "any", meaning: "어떤, 아무" },
    { day: 16, word: "always", meaning: "항상" },
    { day: 16, word: "train", meaning: "기차; 훈련하다" },
    { day: 16, word: "want", meaning: "원하다" },
    { day: 16, word: "water", meaning: "물" },
    { day: 16, word: "backpack", meaning: "배낭" },
    { day: 16, word: "tonight", meaning: "오늘 밤" },
    { day: 16, word: "because", meaning: "~때문에" },
    { day: 16, word: "strong", meaning: "강한, 힘센" },
    { day: 16, word: "fall", meaning: "떨어지다; 가을" },
    { day: 16, word: "under", meaning: "~아래에" },
    { day: 16, word: "glass", meaning: "유리; 잔" },
    { day: 16, word: "when", meaning: "언제; ~할 때" },
    { day: 16, word: "give", meaning: "주다" },
    { day: 16, word: "subway", meaning: "지하철" },
    { day: 16, word: "street", meaning: "거리" },
    { day: 16, word: "police", meaning: "경찰" },
    { day: 16, word: "painter", meaning: "화가" },
    { day: 16, word: "get well", meaning: "회복하다" },
    { day: 16, word: "look around", meaning: "둘러보다" },

    // DAY 17
    { day: 17, word: "busy", meaning: "바쁜" },
    { day: 17, word: "early", meaning: "일찍; 이른" },
    { day: 17, word: "food", meaning: "음식" },
    { day: 17, word: "almost", meaning: "거의" },
    { day: 17, word: "bring", meaning: "가져오다" },
    { day: 17, word: "draw", meaning: "그리다; 당기다" },
    { day: 17, word: "cross", meaning: "건너다; 십자가" },
    { day: 17, word: "over", meaning: "~위에; 끝나고" },
    { day: 17, word: "sing", meaning: "노래하다" },
    { day: 17, word: "doctor", meaning: "의사" },
    { day: 17, word: "special", meaning: "특별한" },
    { day: 17, word: "weak", meaning: "약한" },
    { day: 17, word: "stair", meaning: "계단" },
    { day: 17, word: "which", meaning: "어느 것" },
    { day: 17, word: "road", meaning: "길, 도로" },
    { day: 17, word: "kitchen", meaning: "부엌" },
    { day: 17, word: "snack", meaning: "간식" },
    { day: 17, word: "pair", meaning: "한 쌍, 켤레" },
    { day: 17, word: "these days", meaning: "요즘" },
    { day: 17, word: "get it", meaning: "이해하다; 얻다" },

    // DAY 18
    { day: 18, word: "bottle", meaning: "병" },
    { day: 18, word: "clock", meaning: "시계" },
    { day: 18, word: "dream", meaning: "꿈; 꿈꾸다" },
    { day: 18, word: "complete", meaning: "완전한; 완료하다" },
    { day: 18, word: "season", meaning: "계절" },
    { day: 18, word: "die", meaning: "죽다" },
    { day: 18, word: "store", meaning: "가게; 저장하다" },
    { day: 18, word: "off", meaning: "떨어져; 꺼진" },
    { day: 18, word: "sell", meaning: "팔다" },
    { day: 18, word: "mouth", meaning: "입" },
    { day: 18, word: "glove", meaning: "장갑" },
    { day: 18, word: "dish", meaning: "접시; 요리" },
    { day: 18, word: "heart", meaning: "심장; 마음" },
    { day: 18, word: "picture", meaning: "그림; 사진" },
    { day: 18, word: "leaf", meaning: "나뭇잎" },
    { day: 18, word: "hospital", meaning: "병원" },
    { day: 18, word: "bridge", meaning: "다리" },
    { day: 18, word: "useful", meaning: "유용한" },
    { day: 18, word: "see a doctor", meaning: "진찰받다" },
    { day: 18, word: "pick up", meaning: "집어 들다; 태우러 가다" },

    // DAY 19
    { day: 19, word: "age", meaning: "나이" },
    { day: 19, word: "bath", meaning: "목욕" },
    { day: 19, word: "cousin", meaning: "사촌" },
    { day: 19, word: "enjoy", meaning: "즐기다" },
    { day: 19, word: "ask", meaning: "묻다; 요청하다" },
    { day: 19, word: "only", meaning: "오직, 유일한" },
    { day: 19, word: "take", meaning: "가져가다; (시간이) 걸리다" },
    { day: 19, word: "into", meaning: "~안으로" },
    { day: 19, word: "bread", meaning: "빵" },
    { day: 19, word: "wash", meaning: "씻다" },
    { day: 19, word: "sure", meaning: "확신하는" },
    { day: 19, word: "shoe", meaning: "신발" },
    { day: 19, word: "wind", meaning: "바람" },
    { day: 19, word: "cheap", meaning: "싼" },
    { day: 19, word: "love", meaning: "사랑하다" },
    { day: 19, word: "husband", meaning: "남편" },
    { day: 19, word: "vegetable", meaning: "채소" },
    { day: 19, word: "teach", meaning: "가르치다" },
    { day: 19, word: "do the dishes", meaning: "설거지하다" },
    { day: 19, word: "be over", meaning: "끝나다" },

    // DAY 20
    { day: 20, word: "art", meaning: "예술; 미술" },
    { day: 20, word: "show", meaning: "보여주다; 쇼" },
    { day: 20, word: "airplane", meaning: "비행기" },
    { day: 20, word: "become", meaning: "~이 되다" },
    { day: 20, word: "boat", meaning: "배, 보트" },
    { day: 20, word: "question", meaning: "질문" },
    { day: 20, word: "send", meaning: "보내다" },
    { day: 20, word: "inside", meaning: "안에; 내부" },
    { day: 20, word: "jump", meaning: "뛰다" },
    { day: 20, word: "learn", meaning: "배우다" },
    { day: 20, word: "true", meaning: "사실인, 진실한" },
    { day: 20, word: "move", meaning: "움직이다; 이사하다" },
    { day: 20, word: "dessert", meaning: "후식" },
    { day: 20, word: "square", meaning: "정사각형; 광장" },
    { day: 20, word: "world", meaning: "세계" },
    { day: 20, word: "restaurant", meaning: "식당" },
    { day: 20, word: "picnic", meaning: "소풍" },
    { day: 20, word: "shop", meaning: "가게; 쇼핑하다" },
    { day: 20, word: "for sure", meaning: "확실히" },
    { day: 20, word: "show around", meaning: "구경시켜 주다" },

    // DAY 21
    { day: 21, word: "arrive", meaning: "도착하다" },
    { day: 21, word: "bathroom", meaning: "욕실" },
    { day: 21, word: "case", meaning: "상자; 경우" },
    { day: 21, word: "library", meaning: "도서관" },
    { day: 21, word: "online", meaning: "온라인의" },
    { day: 21, word: "straight", meaning: "똑바로; 곧은" },
    { day: 21, word: "try", meaning: "시도하다; 노력하다" },
    { day: 21, word: "near", meaning: "가까운; 가까이" },
    { day: 21, word: "begin", meaning: "시작하다" },
    { day: 21, word: "finish", meaning: "끝내다" },
    { day: 21, word: "both", meaning: "둘 다" },
    { day: 21, word: "quick", meaning: "빠른" },
    { day: 21, word: "rich", meaning: "부유한" },
    { day: 21, word: "stand", meaning: "서다" },
    { day: 21, word: "sorry", meaning: "미안한" },
    { day: 21, word: "lesson", meaning: "수업; 교훈" },
    { day: 21, word: "wake", meaning: "깨다, 깨우다" },
    { day: 21, word: "let", meaning: "~하게 하다" },
    { day: 21, word: "come true", meaning: "실현되다" },
    { day: 21, word: "one by one", meaning: "하나씩" },

    // DAY 22
    { day: 22, word: "turn", meaning: "돌다; 순서" },
    { day: 22, word: "airport", meaning: "공항" },
    { day: 22, word: "catch", meaning: "잡다; (병에) 걸리다" },
    { day: 22, word: "pretty", meaning: "예쁜; 꽤" },
    { day: 22, word: "breakfast", meaning: "아침 식사" },
    { day: 22, word: "trip", meaning: "여행" },
    { day: 22, word: "hill", meaning: "언덕" },
    { day: 22, word: "as", meaning: "~할 때; ~로서" },
    { day: 22, word: "homework", meaning: "숙제" },
    { day: 22, word: "touch", meaning: "만지다" },
    { day: 22, word: "side", meaning: "쪽, 측면" },
    { day: 22, word: "letter", meaning: "편지; 글자" },
    { day: 22, word: "middle", meaning: "중간의; 가운데" },
    { day: 22, word: "fresh", meaning: "신선한" },
    { day: 22, word: "poor", meaning: "가난한; 불쌍한" },
    { day: 22, word: "soft", meaning: "부드러운" },
    { day: 22, word: "garden", meaning: "정원" },
    { day: 22, word: "gate", meaning: "문, 출입구" },
    { day: 22, word: "try on", meaning: "입어보다" },
    { day: 22, word: "talk on the phone", meaning: "통화하다" },

    // DAY 23
    { day: 23, word: "gift", meaning: "선물; 재능" },
    { day: 23, word: "laugh", meaning: "웃다" },
    { day: 23, word: "clothes", meaning: "옷" },
    { day: 23, word: "strange", meaning: "이상한; 낯선" },
    { day: 23, word: "glad", meaning: "기쁜" },
    { day: 23, word: "ahead", meaning: "앞에" },
    { day: 23, word: "corner", meaning: "모퉁이" },
    { day: 23, word: "artist", meaning: "예술가" },
    { day: 23, word: "restroom", meaning: "화장실" },
    { day: 23, word: "straw", meaning: "빨대; 짚" },
    { day: 23, word: "thank", meaning: "감사하다" },
    { day: 23, word: "windy", meaning: "바람 부는" },
    { day: 23, word: "answer", meaning: "대답하다; 정답" },
    { day: 23, word: "write", meaning: "쓰다" },
    { day: 23, word: "money", meaning: "돈" },
    { day: 23, word: "painting", meaning: "그림" },
    { day: 23, word: "team", meaning: "팀" },
    { day: 23, word: "future", meaning: "미래" },
    { day: 23, word: "turn on", meaning: "켜다" },
    { day: 23, word: "turn off", meaning: "끄다" },
    { day: 23, word: "show up", meaning: "나타나다" },

    // DAY 24
    { day: 24, word: "top", meaning: "맨 위, 정상" },
    { day: 24, word: "active", meaning: "활동적인" },
    { day: 24, word: "bank", meaning: "은행" },
    { day: 24, word: "feed", meaning: "먹이를 주다" },
    { day: 24, word: "style", meaning: "방식; 스타일" },
    { day: 24, word: "throat", meaning: "목구멍" },
    { day: 24, word: "drawing", meaning: "그림" },
    { day: 24, word: "so", meaning: "그래서; 매우" },
    { day: 24, word: "seat", meaning: "좌석" },
    { day: 24, word: "lie", meaning: "눕다; 거짓말하다" },
    { day: 24, word: "fish", meaning: "물고기; 낚시하다" },
    { day: 24, word: "dress", meaning: "드레스; 옷을 입다" },
    { day: 24, word: "away", meaning: "멀리" },
    { day: 24, word: "job", meaning: "일, 직업" },
    { day: 24, word: "right", meaning: "옳은; 오른쪽" },
    { day: 24, word: "museum", meaning: "박물관" },
    { day: 24, word: "lucky", meaning: "운이 좋은" },
    { day: 24, word: "excellent", meaning: "훌륭한" },
    { day: 24, word: "laugh at", meaning: "~을 비웃다" },
    { day: 24, word: "thanks to", meaning: "~덕분에" },

    // DAY 25
    { day: 25, word: "tie", meaning: "묶다; 넥타이" },
    { day: 25, word: "smell", meaning: "냄새가 나다; 냄새" },
    { day: 25, word: "leave", meaning: "떠나다; 남겨두다" },
    { day: 25, word: "change", meaning: "바꾸다; 변화" },
    { day: 25, word: "fan", meaning: "팬; 선풍기" },
    { day: 25, word: "poster", meaning: "포스터" },
    { day: 25, word: "wrong", meaning: "틀린; 나쁜" },
    { day: 25, word: "across", meaning: "건너서" },
    { day: 25, word: "volunteer", meaning: "자원봉사자" },
    { day: 25, word: "type", meaning: "유형, 종류" },
    { day: 25, word: "great", meaning: "위대한; 큰" },
    { day: 25, word: "together", meaning: "함께" },
    { day: 25, word: "hold", meaning: "잡다; 개최하다" },
    { day: 25, word: "exit", meaning: "출구" },
    { day: 25, word: "favorite", meaning: "가장 좋아하는" },
    { day: 25, word: "speed", meaning: "속도" },
    { day: 25, word: "thing", meaning: "것, 물건" },
    { day: 25, word: "stage", meaning: "무대; 단계" },
    { day: 25, word: "get to", meaning: "~에 도착하다" },
    { day: 25, word: "right away", meaning: "즉시" },

    // DAY 26
    { day: 26, word: "action", meaning: "행동; 조치" },
    { day: 26, word: "sun", meaning: "해, 태양" },
    { day: 26, word: "wish", meaning: "바라다; 소원" },
    { day: 26, word: "number", meaning: "숫자; 번호" },
    { day: 26, word: "careful", meaning: "조심하는" },
    { day: 26, word: "fire", meaning: "불; 화재" },
    { day: 26, word: "grandparent", meaning: "조부모" },
    { day: 26, word: "between", meaning: "~사이에" },
    { day: 26, word: "clear", meaning: "맑은; 명확한" },
    { day: 26, word: "break", meaning: "깨다; 휴식" },
    { day: 26, word: "station", meaning: "역" },
    { day: 26, word: "south", meaning: "남쪽" },
    { day: 26, word: "free", meaning: "자유로운; 무료의" },
    { day: 26, word: "smile", meaning: "웃다; 미소" },
    { day: 26, word: "piece", meaning: "조각" },
    { day: 26, word: "umbrella", meaning: "우산" },
    { day: 26, word: "paper", meaning: "종이" },
    { day: 26, word: "ticket", meaning: "표" },
    { day: 26, word: "hold on", meaning: "기다리다; 잡다" },
    { day: 26, word: "take turns", meaning: "교대로 하다" },

    // DAY 27
    { day: 27, word: "add", meaning: "더하다" },
    { day: 27, word: "example", meaning: "예, 보기" },
    { day: 27, word: "care", meaning: "돌봄; 주의" },
    { day: 27, word: "sink", meaning: "가라앉다; 싱크대" },
    { day: 27, word: "manager", meaning: "관리자" },
    { day: 27, word: "ocean", meaning: "대양, 바다" },
    { day: 27, word: "help", meaning: "돕다" },
    { day: 27, word: "sunny", meaning: "화창한" },
    { day: 27, word: "choose", meaning: "선택하다" },
    { day: 27, word: "dentist", meaning: "치과 의사" },
    { day: 27, word: "swim", meaning: "수영하다" },
    { day: 27, word: "throw", meaning: "던지다" },
    { day: 27, word: "front", meaning: "앞" },
    { day: 27, word: "living room", meaning: "거실" },
    { day: 27, word: "message", meaning: "메시지" },
    { day: 27, word: "need", meaning: "필요하다" },
    { day: 27, word: "west", meaning: "서쪽" },
    { day: 27, word: "rule", meaning: "규칙" },
    { day: 27, word: "ask for", meaning: "요청하다" },
    { day: 27, word: "take off", meaning: "벗다; 이륙하다" },

    // DAY 28
    { day: 28, word: "tell", meaning: "말하다" },
    { day: 28, word: "bone", meaning: "뼈" },
    { day: 28, word: "stone", meaning: "돌" },
    { day: 28, word: "keep", meaning: "유지하다; 계속하다" },
    { day: 28, word: "fix", meaning: "고치다" },
    { day: 28, word: "diary", meaning: "일기" },
    { day: 28, word: "mathematics", meaning: "수학" },
    { day: 28, word: "below", meaning: "~아래에" },
    { day: 28, word: "concert", meaning: "콘서트" },
    { day: 28, word: "fact", meaning: "사실" },
    { day: 28, word: "moment", meaning: "순간" },
    { day: 28, word: "soon", meaning: "곧" },
    { day: 28, word: "park", meaning: "공원; 주차하다" },
    { day: 28, word: "triangle", meaning: "삼각형" },
    { day: 28, word: "once", meaning: "한 번; 옛날에" },
    { day: 28, word: "tired", meaning: "피곤한" },
    { day: 28, word: "hurt", meaning: "다치게 하다; 아프다" },
    { day: 28, word: "line", meaning: "선; 줄" },
    { day: 28, word: "get on", meaning: "타다" },
    { day: 28, word: "get off", meaning: "내리다" },
    { day: 28, word: "for free", meaning: "공짜로" },

    // DAY 29
    { day: 29, word: "also", meaning: "또한" },
    { day: 29, word: "activity", meaning: "활동" },
    { day: 29, word: "stop", meaning: "멈추다" },
    { day: 29, word: "hope", meaning: "희망하다" },
    { day: 29, word: "science", meaning: "과학" },
    { day: 29, word: "cost", meaning: "비용이 들다; 비용" },
    { day: 29, word: "bookstore", meaning: "서점" },
    { day: 29, word: "delicious", meaning: "맛있는" },
    { day: 29, word: "wood", meaning: "나무; 목재" },
    { day: 29, word: "musician", meaning: "음악가" },
    { day: 29, word: "land", meaning: "땅; 착륙하다" },
    { day: 29, word: "mall", meaning: "쇼핑몰" },
    { day: 29, word: "point", meaning: "점수; 요점; 가리키다" },
    { day: 29, word: "role", meaning: "역할" },
    { day: 29, word: "step", meaning: "걸음; 단계" },
    { day: 29, word: "taste", meaning: "맛; 맛이 나다" },
    { day: 29, word: "text", meaning: "글; 문자" },
    { day: 29, word: "moon", meaning: "달" },
    { day: 29, word: "run away", meaning: "달아나다" },
    { day: 29, word: "line up", meaning: "줄을 서다" },

    // DAY 30
    { day: 30, word: "plan", meaning: "계획; 계획하다" },
    { day: 30, word: "best", meaning: "최고의" },
    { day: 30, word: "carefully", meaning: "조심스럽게" },
    { day: 30, word: "forget", meaning: "잊다" },
    { day: 30, word: "review", meaning: "복습하다; 검토하다" },
    { day: 30, word: "agree", meaning: "동의하다" },
    { day: 30, word: "teen", meaning: "10대" },
    { day: 30, word: "above", meaning: "~위에" },
    { day: 30, word: "scientist", meaning: "과학자" },
    { day: 30, word: "surprise", meaning: "놀라움; 놀라게 하다" },
    { day: 30, word: "other", meaning: "다른" },
    { day: 30, word: "magic", meaning: "마술" },
    { day: 30, word: "toe", meaning: "발가락" },
    { day: 30, word: "skill", meaning: "기술" },
    { day: 30, word: "wife", meaning: "아내" },
    { day: 30, word: "mix", meaning: "섞다" },
    { day: 30, word: "just", meaning: "그저; 방금" },
    { day: 30, word: "tasty", meaning: "맛있는" },
    { day: 30, word: "give up", meaning: "포기하다" },
    { day: 30, word: "take care of", meaning: "~을 돌보다" },

    // DAY 31
    { day: 31, word: "wide", meaning: "넓은" },
    { day: 31, word: "area", meaning: "지역" },
    { day: 31, word: "band", meaning: "밴드; 끈" },
    { day: 31, word: "nail", meaning: "손톱; 못" },
    { day: 31, word: "expensive", meaning: "비싼" },
    { day: 31, word: "correct", meaning: "정확한; 수정하다" },
    { day: 31, word: "photograph", meaning: "사진" },
    { day: 31, word: "along", meaning: "~을 따라서" },
    { day: 31, word: "build", meaning: "짓다" },
    { day: 31, word: "proud", meaning: "자랑스러운" },
    { day: 31, word: "shake", meaning: "흔들다" },
    { day: 31, word: "ring", meaning: "반지; 울리다" },
    { day: 31, word: "shape", meaning: "모양" },
    { day: 31, word: "hunt", meaning: "사냥하다" },
    { day: 31, word: "drop", meaning: "떨어뜨리다" },
    { day: 31, word: "sunglasses", meaning: "선글라스" },
    { day: 31, word: "film", meaning: "영화; 필름" },
    { day: 31, word: "office", meaning: "사무실" },
    { day: 31, word: "each other", meaning: "서로" },
    { day: 31, word: "do one's best", meaning: "최선을 다하다" },

    // DAY 32
    { day: 32, word: "few", meaning: "거의 없는" },
    { day: 32, word: "danger", meaning: "위험" },
    { day: 32, word: "camp", meaning: "캠프; 야영하다" },
    { day: 32, word: "building", meaning: "건물" },
    { day: 32, word: "afraid", meaning: "두려워하는" },
    { day: 32, word: "basket", meaning: "바구니" },
    { day: 32, word: "note", meaning: "쪽지; 노트" },
    { day: 32, word: "until", meaning: "~까지" },
    { day: 32, word: "singer", meaning: "가수" },
    { day: 32, word: "someone", meaning: "누군가" },
    { day: 32, word: "teenager", meaning: "10대 청소년" },
    { day: 32, word: "musical", meaning: "음악의; 뮤지컬" },
    { day: 32, word: "bake", meaning: "굽다" },
    { day: 32, word: "pot", meaning: "냄비" },
    { day: 32, word: "plant", meaning: "식물; 심다" },
    { day: 32, word: "seafood", meaning: "해산물" },
    { day: 32, word: "island", meaning: "섬" },
    { day: 32, word: "grass", meaning: "풀, 잔디" },
    { day: 32, word: "stop by", meaning: "들르다" },
    { day: 32, word: "be proud of", meaning: "~을 자랑스러워하다" },

    // DAY 33
    { day: 33, word: "blow", meaning: "불다" },
    { day: 33, word: "cheer", meaning: "환호하다; 응원하다" },
    { day: 33, word: "false", meaning: "틀린; 거짓의" },
    { day: 33, word: "gas", meaning: "가스; 기체" },
    { day: 33, word: "lose", meaning: "잃다; 지다" },
    { day: 33, word: "history", meaning: "역사" },
    { day: 33, word: "textbook", meaning: "교과서" },
    { day: 33, word: "through", meaning: "~을 통하여" },
    { day: 33, word: "visit", meaning: "방문하다" },
    { day: 33, word: "count", meaning: "세다" },
    { day: 33, word: "forest", meaning: "숲" },
    { day: 33, word: "hall", meaning: "복도; 홀" },
    { day: 33, word: "safe", meaning: "안전한" },
    { day: 33, word: "pass", meaning: "지나가다; 합격하다" },
    { day: 33, word: "shadow", meaning: "그림자" },
    { day: 33, word: "miss", meaning: "놓치다; 그리워하다" },
    { day: 33, word: "same", meaning: "같은" },
    { day: 33, word: "tail", meaning: "꼬리" },
    { day: 33, word: "a little", meaning: "약간의" },
    { day: 33, word: "fall in love", meaning: "사랑에 빠지다" },

    // DAY 34
    { day: 34, word: "oil", meaning: "기름" },
    { day: 34, word: "difficult", meaning: "어려운" },
    { day: 34, word: "travel", meaning: "여행하다" },
    { day: 34, word: "part", meaning: "부분" },
    { day: 34, word: "mirror", meaning: "거울" },
    { day: 34, word: "boring", meaning: "지루한" },
    { day: 34, word: "examination", meaning: "시험" },
    { day: 34, word: "check", meaning: "확인하다" },
    { day: 34, word: "receive", meaning: "받다" },
    { day: 34, word: "different", meaning: "다른" },
    { day: 34, word: "enough", meaning: "충분한" },
    { day: 34, word: "worry", meaning: "걱정하다" },
    { day: 34, word: "still", meaning: "여전히; 정지한" },
    { day: 34, word: "gym", meaning: "체육관" },
    { day: 34, word: "spend", meaning: "쓰다, 보내다" },
    { day: 34, word: "rest", meaning: "휴식; 쉬다" },
    { day: 34, word: "climb", meaning: "오르다" },
    { day: 34, word: "lazy", meaning: "게으른" },
    { day: 34, word: "cheer up", meaning: "기운 내다" },
    { day: 34, word: "write down", meaning: "받아적다" },

    // DAY 35
    { day: 35, word: "chef", meaning: "요리사" },
    { day: 35, word: "boil", meaning: "끓다, 끓이다" },
    { day: 35, word: "exciting", meaning: "신나는" },
    { day: 35, word: "already", meaning: "이미, 벌써" },
    { day: 35, word: "speech", meaning: "연설" },
    { day: 35, word: "guess", meaning: "추측하다" },
    { day: 35, word: "weight", meaning: "무게" },
    { day: 35, word: "anything", meaning: "무엇이든" },
    { day: 35, word: "sometimes", meaning: "가끔" },
    { day: 35, word: "river", meaning: "강" },
    { day: 35, word: "farm", meaning: "농장" },
    { day: 35, word: "remember", meaning: "기억하다" },
    { day: 35, word: "interest", meaning: "흥미, 관심" },
    { day: 35, word: "most", meaning: "대부분의; 가장 많은" },
    { day: 35, word: "place", meaning: "장소" },
    { day: 35, word: "company", meaning: "회사; 동료" },
    { day: 35, word: "space", meaning: "공간; 우주" },
    { day: 35, word: "health", meaning: "건강" },
    { day: 35, word: "hand in", meaning: "제출하다" },
    { day: 35, word: "take out", meaning: "꺼내다" },

    // DAY 36
    { day: 36, word: "bored", meaning: "지루해하는" },
    { day: 36, word: "goal", meaning: "목표; 골" },
    { day: 36, word: "healthy", meaning: "건강한" },
    { day: 36, word: "farmer", meaning: "농부" },
    { day: 36, word: "pay", meaning: "지불하다" },
    { day: 36, word: "stomach", meaning: "위, 배" },
    { day: 36, word: "something", meaning: "무언가" },
    { day: 36, word: "while", meaning: "~하는 동안" },
    { day: 36, word: "beat", meaning: "치다; 이기다" },
    { day: 36, word: "hang", meaning: "걸다" },
    { day: 36, word: "lovely", meaning: "사랑스러운" },
    { day: 36, word: "honest", meaning: "정직한" },
    { day: 36, word: "understand", meaning: "이해하다" },
    { day: 36, word: "interesting", meaning: "재미있는" },
    { day: 36, word: "rope", meaning: "밧줄" },
    { day: 36, word: "pour", meaning: "붓다, 따르다" },
    { day: 36, word: "club", meaning: "동아리, 클럽" },
    { day: 36, word: "writer", meaning: "작가" },
    { day: 36, word: "on time", meaning: "정각에" },
    { day: 36, word: "be worried about", meaning: "~을 걱정하다" },

    // DAY 37
    { day: 37, word: "list", meaning: "목록" },
    { day: 37, word: "project", meaning: "프로젝트" },
    { day: 37, word: "carry", meaning: "나르다" },
    { day: 37, word: "empty", meaning: "빈" },
    { day: 37, word: "famous", meaning: "유명한" },
    { day: 37, word: "raise", meaning: "올리다; 기르다" },
    { day: 37, word: "drink", meaning: "마시다" },
    { day: 37, word: "behind", meaning: "뒤에" },
    { day: 37, word: "stay", meaning: "머무르다" },
    { day: 37, word: "another", meaning: "또 다른" },
    { day: 37, word: "surprising", meaning: "놀라운" },
    { day: 37, word: "outside", meaning: "밖에" },
    { day: 37, word: "stick", meaning: "막대기; 붙이다" },
    { day: 37, word: "vacation", meaning: "방학, 휴가" },
    { day: 37, word: "interested", meaning: "흥미 있어 하는" },
    { day: 37, word: "dead", meaning: "죽은" },
    { day: 37, word: "beef", meaning: "소고기" },
    { day: 37, word: "excuse", meaning: "변명; 용서하다" },
    { day: 37, word: "work out", meaning: "운동하다; 해결하다" },
    { day: 37, word: "hang out", meaning: "어울려 놀다" },

    // DAY 38
    { day: 38, word: "believe", meaning: "믿다" },
    { day: 38, word: "calm", meaning: "침착한" },
    { day: 38, word: "dangerous", meaning: "위험한" },
    { day: 38, word: "festival", meaning: "축제" },
    { day: 38, word: "shy", meaning: "수줍은" },
    { day: 38, word: "lonely", meaning: "외로운" },
    { day: 38, word: "spicy", meaning: "매운" },
    { day: 38, word: "wonder", meaning: "궁금하다" },
    { day: 38, word: "solve", meaning: "풀다, 해결하다" },
    { day: 38, word: "fail", meaning: "실패하다" },
    { day: 38, word: "neighbor", meaning: "이웃" },
    { day: 38, word: "ground", meaning: "땅" },
    { day: 38, word: "circle", meaning: "원" },
    { day: 38, word: "important", meaning: "중요한" },
    { day: 38, word: "pond", meaning: "연못" },
    { day: 38, word: "roll", meaning: "구르다" },
    { day: 38, word: "dear", meaning: "친애하는; 소중한" },
    { day: 38, word: "practice", meaning: "연습하다; 연습" },
    { day: 38, word: "get out of", meaning: "~에서 나가다" },
    { day: 38, word: "give it a try", meaning: "시도해보다" },

    // DAY 39
    { day: 39, word: "bill", meaning: "청구서; 지폐" },
    { day: 39, word: "collect", meaning: "모으다" },
    { day: 39, word: "surprised", meaning: "놀란" },
    { day: 39, word: "join", meaning: "가입하다; 함께하다" },
    { day: 39, word: "blank", meaning: "빈칸; 비어있는" },
    { day: 39, word: "problem", meaning: "문제" },
    { day: 39, word: "crash", meaning: "충돌하다" },
    { day: 39, word: "however", meaning: "그러나" },
    { day: 39, word: "secret", meaning: "비밀" },
    { day: 39, word: "record", meaning: "기록; 기록하다" },
    { day: 39, word: "hometown", meaning: "고향" },
    { day: 39, word: "race", meaning: "경주" },
    { day: 39, word: "bowl", meaning: "그릇, 사발" },
    { day: 39, word: "daily", meaning: "매일의" },
    { day: 39, word: "newspaper", meaning: "신문" },
    { day: 39, word: "tip", meaning: "조언; 팁; 끝" },
    { day: 39, word: "wonderful", meaning: "멋진" },
    { day: 39, word: "own", meaning: "소유하다; 자신의" },
    { day: 39, word: "be interested in", meaning: "~에 관심이 있다" },
    { day: 39, word: "believe in", meaning: "~을 믿다" },

    // DAY 40
    { day: 40, word: "lift", meaning: "들어 올리다" },
    { day: 40, word: "bottom", meaning: "바닥, 맨 아래" },
    { day: 40, word: "hole", meaning: "구멍" },
    { day: 40, word: "dialogue", meaning: "대화" },
    { day: 40, word: "real", meaning: "진짜의" },
    { day: 40, word: "news", meaning: "뉴스, 소식" },
    { day: 40, word: "jungle", meaning: "정글" },
    { day: 40, word: "form", meaning: "형태; 형성하다" },
    { day: 40, word: "sunlight", meaning: "햇빛" },
    { day: 40, word: "contest", meaning: "대회" },
    { day: 40, word: "brave", meaning: "용감한" },
    { day: 40, word: "hurry", meaning: "서두르다" },
    { day: 40, word: "magazine", meaning: "잡지" },
    { day: 40, word: "welcome", meaning: "환영하다" },
    { day: 40, word: "sleepy", meaning: "졸리는" },
    { day: 40, word: "protect", meaning: "보호하다" },
    { day: 40, word: "matter", meaning: "문제; 중요하다" },
    { day: 40, word: "past", meaning: "과거" },
    { day: 40, word: "take place", meaning: "일어나다, 개최되다" },
    { day: 40, word: "not anymore", meaning: "더 이상 ~않다" },

    // DAY 41
    { day: 41, word: "fry", meaning: "튀기다" },
    { day: 41, word: "advice", meaning: "충고" },
    { day: 41, word: "course", meaning: "과정; 코스" },
    { day: 41, word: "habit", meaning: "습관" },
    { day: 41, word: "sign", meaning: "표지판; 서명하다" },
    { day: 41, word: "perfect", meaning: "완벽한" },
    { day: 41, word: "heat", meaning: "열, 더위" },
    { day: 41, word: "without", meaning: "~없이" },
    { day: 41, word: "colorful", meaning: "다채로운" },
    { day: 41, word: "never", meaning: "결코 ~않다" },
    { day: 41, word: "tea", meaning: "차" },
    { day: 41, word: "trouble", meaning: "문제, 어려움" },
    { day: 41, word: "okay", meaning: "괜찮은" },
    { day: 41, word: "honey", meaning: "꿀" },
    { day: 41, word: "sport", meaning: "스포츠" },
    { day: 41, word: "friendly", meaning: "친절한" },
    { day: 41, word: "serve", meaning: "제공하다" },
    { day: 41, word: "uniform", meaning: "유니폼" },
    { day: 41, word: "all the time", meaning: "항상" },
    { day: 41, word: "for a while", meaning: "잠시 동안" },

    // DAY 42
    { day: 42, word: "field", meaning: "들판; 분야" },
    { day: 42, word: "blind", meaning: "눈이 먼" },
    { day: 42, word: "center", meaning: "중심" },
    { day: 42, word: "headache", meaning: "두통" },
    { day: 42, word: "score", meaning: "점수" },
    { day: 42, word: "pilot", meaning: "조종사" },
    { day: 42, word: "everything", meaning: "모든 것" },
    { day: 42, word: "during", meaning: "~동안" },
    { day: 42, word: "luck", meaning: "행운" },
    { day: 42, word: "nickname", meaning: "별명" },
    { day: 42, word: "mistake", meaning: "실수" },
    { day: 42, word: "greet", meaning: "인사하다" },
    { day: 42, word: "sharp", meaning: "날카로운" },
    { day: 42, word: "usual", meaning: "평소의" },
    { day: 42, word: "cough", meaning: "기침하다" },
    { day: 42, word: "fashion", meaning: "유행; 패션" },
    { day: 42, word: "plate", meaning: "접시" },
    { day: 42, word: "meal", meaning: "식사" },
    { day: 42, word: "of course", meaning: "물론" },
    { day: 42, word: "on one's own", meaning: "혼자 힘으로" },

    // DAY 43
    { day: 43, word: "mind", meaning: "마음" },
    { day: 43, word: "win", meaning: "이기다" },
    { day: 43, word: "amazing", meaning: "놀라운" },
    { day: 43, word: "borrow", meaning: "빌리다" },
    { day: 43, word: "comic", meaning: "만화의; 웃기는" },
    { day: 43, word: "garbage", meaning: "쓰레기" },
    { day: 43, word: "sale", meaning: "판매" },
    { day: 43, word: "nothing", meaning: "아무것도 아님" },
    { day: 43, word: "director", meaning: "감독" },
    { day: 43, word: "cell phone", meaning: "휴대전화" },
    { day: 43, word: "tour", meaning: "여행" },
    { day: 43, word: "share", meaning: "공유하다" },
    { day: 43, word: "wrap", meaning: "싸다, 포장하다" },
    { day: 43, word: "energy", meaning: "에너지" },
    { day: 43, word: "gather", meaning: "모으다" },
    { day: 43, word: "happen", meaning: "일어나다" },
    { day: 43, word: "usually", meaning: "보통" },
    { day: 43, word: "prize", meaning: "상" },
    { day: 43, word: "cut down", meaning: "줄이다" },
    { day: 43, word: "would like to", meaning: "~하고 싶다" },

    // DAY 44
    { day: 44, word: "joy", meaning: "기쁨" },
    { day: 44, word: "award", meaning: "상" },
    { day: 44, word: "nurse", meaning: "간호사" },
    { day: 44, word: "quiet", meaning: "조용한" },
    { day: 44, word: "cartoon", meaning: "만화" },
    { day: 44, word: "excited", meaning: "신이 난" },
    { day: 44, word: "melt", meaning: "녹다" },
    { day: 44, word: "grade", meaning: "학년; 성적" },
    { day: 44, word: "helpful", meaning: "도움이 되는" },
    { day: 44, word: "post", meaning: "우편; 게시하다" },
    { day: 44, word: "sentence", meaning: "문장" },
    { day: 44, word: "trash", meaning: "쓰레기" },
    { day: 44, word: "design", meaning: "디자인" },
    { day: 44, word: "subject", meaning: "주제; 과목" },
    { day: 44, word: "match", meaning: "경기; 성냥" },
    { day: 44, word: "village", meaning: "마을" },
    { day: 44, word: "insect", meaning: "곤충" },
    { day: 44, word: "possible", meaning: "가능한" },
    { day: 44, word: "count on", meaning: "믿다, 의지하다" },
    { day: 44, word: "at the same time", meaning: "동시에" },

    // DAY 45
    { day: 45, word: "event", meaning: "사건; 행사" },
    { day: 45, word: "nature", meaning: "자연" },
    { day: 45, word: "level", meaning: "수준" },
    { day: 45, word: "create", meaning: "창조하다" },
    { day: 45, word: "shout", meaning: "소리치다" },
    { day: 45, word: "animation", meaning: "만화영화" },
    { day: 45, word: "cause", meaning: "원인" },
    { day: 45, word: "information", meaning: "정보" },
    { day: 45, word: "designer", meaning: "디자이너" },
    { day: 45, word: "pack", meaning: "짐을 싸다" },
    { day: 45, word: "meeting", meaning: "회의" },
    { day: 45, word: "quiz", meaning: "퀴즈" },
    { day: 45, word: "wise", meaning: "현명한" },
    { day: 45, word: "fantastic", meaning: "환상적인" },
    { day: 45, word: "peace", meaning: "평화" },
    { day: 45, word: "opinion", meaning: "의견" },
    { day: 45, word: "relax", meaning: "쉬다" },
    { day: 45, word: "flat", meaning: "평평한" },
    { day: 45, word: "throw away", meaning: "버리다" },
    { day: 45, word: "live next door", meaning: "옆집에 살다" },

    // DAY 46
    { day: 46, word: "hero", meaning: "영웅" },
    { day: 46, word: "save", meaning: "구하다; 저축하다" },
    { day: 46, word: "main", meaning: "주된" },
    { day: 46, word: "final", meaning: "마지막의" },
    { day: 46, word: "even", meaning: "심지어" },
    { day: 46, word: "human", meaning: "인간" },
    { day: 46, word: "scared", meaning: "무서워하는" },
    { day: 46, word: "court", meaning: "법정; 코트" },
    { day: 46, word: "interview", meaning: "인터뷰" },
    { day: 46, word: "block", meaning: "막다; 블록" },
    { day: 46, word: "float", meaning: "뜨다" },
    { day: 46, word: "decide", meaning: "결정하다" },
    { day: 46, word: "order", meaning: "주문하다; 순서" },
    { day: 46, word: "creative", meaning: "창의적인" },
    { day: 46, word: "result", meaning: "결과" },
    { day: 46, word: "wave", meaning: "파도; 흔들다" },
    { day: 46, word: "fair", meaning: "공정한" },
    { day: 46, word: "member", meaning: "회원" },
    { day: 46, word: "upside down", meaning: "거꾸로" },
    { day: 46, word: "turn over", meaning: "뒤집다" },

    // DAY 47
    { day: 47, word: "item", meaning: "품목, 아이템" },
    { day: 47, word: "character", meaning: "성격; 등장인물" },
    { day: 47, word: "popular", meaning: "인기 있는" },
    { day: 47, word: "scene", meaning: "장면" },
    { day: 47, word: "topic", meaning: "주제" },
    { day: 47, word: "exercise", meaning: "운동" },
    { day: 47, word: "choice", meaning: "선택" },
    { day: 47, word: "promise", meaning: "약속" },
    { day: 47, word: "everywhere", meaning: "어디에나" },
    { day: 47, word: "follow", meaning: "따르다" },
    { day: 47, word: "language", meaning: "언어" },
    { day: 47, word: "hiking", meaning: "하이킹" },
    { day: 47, word: "recipe", meaning: "요리법" },
    { day: 47, word: "simple", meaning: "단순한" },
    { day: 47, word: "traveler", meaning: "여행자" },
    { day: 47, word: "yet", meaning: "아직" },
    { day: 47, word: "introduce", meaning: "소개하다" },
    { day: 47, word: "zone", meaning: "구역" },
    { day: 47, word: "make it", meaning: "해내다" },
    { day: 47, word: "over and over", meaning: "반복해서" },

    // DAY 48
    { day: 48, word: "poem", meaning: "시" },
    { day: 48, word: "view", meaning: "경치; 관점" },
    { day: 48, word: "champion", meaning: "챔피언" },
    { day: 48, word: "discover", meaning: "발견하다" },
    { day: 48, word: "focus", meaning: "집중하다" },
    { day: 48, word: "huge", meaning: "거대한" },
    { day: 48, word: "marry", meaning: "결혼하다" },
    { day: 48, word: "reach", meaning: "도달하다" },
    { day: 48, word: "tradition", meaning: "전통" },
    { day: 48, word: "script", meaning: "대본" },
    { day: 48, word: "president", meaning: "대통령" },
    { day: 48, word: "nobody", meaning: "아무도 ~않다" },
    { day: 48, word: "hunter", meaning: "사냥꾼" },
    { day: 48, word: "please", meaning: "제발; 기쁘게 하다" },
    { day: 48, word: "machine", meaning: "기계" },
    { day: 48, word: "owner", meaning: "주인" },
    { day: 48, word: "factory", meaning: "공장" },
    { day: 48, word: "tower", meaning: "탑" },
    { day: 48, word: "turn down", meaning: "거절하다" },
    { day: 48, word: "such as", meaning: "~와 같은" },

    // DAY 49
    { day: 49, word: "common", meaning: "흔한; 공통의" },
    { day: 49, word: "enemy", meaning: "적" },
    { day: 49, word: "guide", meaning: "안내하다; 가이드" },
    { day: 49, word: "lock", meaning: "잠그다" },
    { day: 49, word: "memory", meaning: "기억" },
    { day: 49, word: "program", meaning: "프로그램" },
    { day: 49, word: "maybe", meaning: "아마도" },
    { day: 49, word: "power", meaning: "힘" },
    { day: 49, word: "royal", meaning: "왕실의" },
    { day: 49, word: "wild", meaning: "야생의" },
    { day: 49, word: "slide", meaning: "미끄러지다" },
    { day: 49, word: "national", meaning: "국가의" },
    { day: 49, word: "outdoor", meaning: "야외의" },
    { day: 49, word: "plastic", meaning: "플라스틱" },
    { day: 49, word: "report", meaning: "보고하다" },
    { day: 49, word: "culture", meaning: "문화" },
    { day: 49, word: "recycle", meaning: "재활용하다" },
    { day: 49, word: "traditional", meaning: "전통적인" },
    { day: 49, word: "be on time", meaning: "제시간에 오다" },
    { day: 49, word: "millions of", meaning: "수백만의" },

    // DAY 50
    { day: 50, word: "invite", meaning: "초대하다" },
    { day: 50, word: "mean", meaning: "의미하다" },
    { day: 50, word: "total", meaning: "전체의; 합계" },
    { day: 50, word: "coupon", meaning: "쿠폰" },
    { day: 50, word: "curious", meaning: "호기심 많은" },
    { day: 50, word: "finally", meaning: "마침내" },
    { day: 50, word: "powerful", meaning: "강력한" },
    { day: 50, word: "return", meaning: "돌아오다" },
    { day: 50, word: "visitor", meaning: "방문객" },
    { day: 50, word: "desert", meaning: "사막" },
    { day: 50, word: "refrigerator", meaning: "냉장고" },
    { day: 50, word: "shower", meaning: "샤워" },
    { day: 50, word: "freeze", meaning: "얼다" },
    { day: 50, word: "partner", meaning: "파트너" },
    { day: 50, word: "tongue", meaning: "혀" },
    { day: 50, word: "spread", meaning: "펼치다; 퍼지다" },
    { day: 50, word: "beauty", meaning: "아름다움" },
    { day: 50, word: "reporter", meaning: "기자" },
    { day: 50, word: "once upon a time", meaning: "옛날 옛적에" },
    { day: 50, word: "have in common", meaning: "공통점이 있다" }
];
